export const govtStyles = {
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  textMain: {
    flexDirection: 'column',
    margin: 12,
    alignContent: 'center',
  },
  text: {
    color: '#000000',
    fontFamily: 'BakbakOne-Regular',
    fontSize: 25,
    lineHeight: 35,
    width: 207,
    height: 70,
    top: 85,
    left: 21,
  },
  paragraph: {
    left: 22,
    top: 80,
    width: 324,
    fontSize: 15,
    fontFamily: 'Inter',
    color: '#AAAAAA',
  },
  borderBox: {
    width: 320,
    alignSelf: 'center',
    top: 180,
    height: 92,
    left: 0,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#C4C4C4',
    marginBottom: 30,
  },
  idcardIcon: {
    textAlign: 'center',
    height: 66,
    margin: 13,
  },
  insideBox: {
    borderWidth: 1,
    margin: 10,
    height: 66,
    backgroundColor: '#DCC7E1',
    borderRadius: 40,
    borderColor: '#DCC7E1',
  },
  textIDCard: {
    fontFamily: 'BakbakOne-Regular',
    fontSize: 18,
    width: 143,
    color: '#000000',
  },
  textCard: {
    fontFamily: 'Inter',
    color: '#AAAAAA',
    fontSize: 12,
    width: 193,
    top: 5,
    lineHeight: 15,
    letterSpacing: -0.017
  },
  moveRight: {
    left: -15,
    textAlign: 'center',
    marginTop: 30,
    color: '#797979'
  },
  govtPageArrowIcon: {
    left: 300,
    top: 239,
    position: 'absolute',
    backgroundColor: '#DCC7E1',
    borderRadius: 20,
  },
};
